Start the package named by .godir when start() is invoked

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -4,70 +4,50 @@ STOPTIMEOUT=10
 FMT="%a %b %d %Y %H:%M:%S GMT%z (%Z)"
 
 function is_go_service_running() {
-    if [ -f $OPENSHIFT_GO_PID_DIR/node.pid ]; then
-        node_pid=$( cat $OPENSHIFT_GO_DIR/pid/go.pid 2> /dev/null )
-        myid=$( id -u )
-        if `ps --pid $node_pid 2>&1 | grep node > /dev/null 2>&1`  ||  \
-           `pgrep -x node -u $myid > /dev/null 2>&1`; then
+    if [ -f $OPENSHIFT_GO_DIR/pid/go.pid ]; then
+        go_pid=$( cat $OPENSHIFT_GO_DIR/pid/go.pid 2> /dev/null )
+        if `ps --pid $go_pid 2>&1`; then
             return 0
         fi
     fi
 
     return 1
-
-}  #  End of function  _is_node_running.
+}
 
 function status() {
-    if [ is_node_service_running ]; then
+    if [ is_go_service_running ]; then
         client_result "Application is running"
     else
         client_result "Application is not running"
     fi
-}  #  End of function  status.
+}
 
 
 function start() {
-    envf="$OPENSHIFT_GO_DIR/configuration/go.env"
     logf="$OPENSHIFT_GO_LOG_DIR/go.log"
-
-    #  Source environment if it exists.
-    [ -f "$envf" ]  &&  source "$envf"
-
-    #  Ensure we have script file.
-    #node_app=${node_app:-"server.js"}
-
-    #if [ ! -h "$OPENSHIFT_REPO_DIR/../node_modules" ]; then
-    #   ln -s ../../nodejs-0.6/node_modules $OPENSHIFT_REPO_DIR/../node_modules
-    #fi
-
     pushd "$OPENSHIFT_REPO_DIR" > /dev/null
     {
-        echo "`date +"$FMT"`: Starting application '$OPENSHIFT_APP_NAME' ..."
-        if [ ! -f "$OPENSHIFT_REPO_DIR/package.json" ]; then
-            echo "    Script       = $node_app"
-            echo "    Script Args  = $node_app_args"
-            echo "    Node Options = $node_opts"
+        godir=$(cat .godir)
+        package=$(basename $godir)
+
+        if [ -f "bin/$package" ]; then
+            echo "`date +"$FMT"`: Starting application '$OPENSHIFT_APP_NAME' ..."
+
+            nohup "bin/$package" >> $logf 2>&1 &
+
+            ret=$?
+            npid=$!
+            if [ $ret -eq 0 ]; then
+                echo "$npid" > "$OPENSHIFT_GO_DIR/pid/go.pid"
+            else
+                echo "Application '$OPENSHIFT_APP_NAME' failed to start - $ret" 1>&2
+                exit $ret
+            fi
+        else
+            echo "WARN: Could not find the compiled application, will not start"
         fi
     } >> $logf
-
-
-    #if [ -f "$OPENSHIFT_REPO_DIR/.openshift/markers/hot_deploy" ]; then
-    #    nohup supervisor -e 'node|js|coffee' -- $script_n_opts  >> $logf 2>&1 &
-    #else
-    #    nohup $executor_cmdline >> $logf 2>&1 &
-    #fi
-
-    ret=$?
-    npid=$!
-    popd > /dev/null
-    if [ $ret -eq 0 ]; then
-        echo "$npid" > "$OPENSHIFT_GO_DIR/pid/go.pid"
-    else
-        echo "Application '$OPENSHIFT_APP_NAME' failed to start - $ret" 1>&2
-    #    exit $ret
-    fi
 }
-
 
 function stop() {
     if [ -f $OPENSHIFT_GO_DIR/pid/go.pid ]; then
@@ -75,7 +55,7 @@ function stop() {
     fi
 
     if [ -n "$go_pid" ]; then
-        logf="$OPENSHIFT_GO_LOG_DIR/node.log"
+        logf="$OPENSHIFT_GO_LOG_DIR/go.log"
         echo "`date +"$FMT"`: Stopping application '$OPENSHIFT_APP_NAME' ..." >> $logf
         /bin/kill $go_pid
         ret=$?
@@ -97,7 +77,6 @@ function stop() {
     fi
 }
 
-
 function restart() {
     stop
     start
@@ -108,13 +87,11 @@ function build() {
 }
 
 function post-deploy() {
-    #
-    echo 'noop'
+    echo
 }
 
 function pre-build() {
-    #
-    echo 'noop'
+    echo
 }
 
 function tidy() {
